"""Deterministic merge of per-part FeatureScript snippets."""

from __future__ import annotations

from datetime import datetime, timezone
import textwrap
from typing import Sequence

from .generator import PartResult
from .models import AssemblyPlan


_FS_HEADER = """\
FeatureScript 2399;
import(path : "onshape/std/geometry.fs", version : "2399.0");
"""

_FEATURE_TEMPLATE = """\
annotation {{ "Feature Type Name" : "{feature_name}" }}
export const {func_name} = defineFeature(function(context is Context, id is Id, definition is map)
precondition
{{}}
{{
{body}
}});
"""


def merge_featurescript(
    plan: AssemblyPlan,
    results: Sequence[PartResult],
    *,
    feature_name: str | None = None,
) -> str:
    assembly_name = plan.assembly_name
    display_name = feature_name or assembly_name.replace("_", " ").title()
    func_name = _to_camel_case(assembly_name)
    errors = [(result.part_id, result.error) for result in results if result.error]

    part_sections: list[str] = []
    for result in results:
        if result.error:
            section = (
                f"    // [ERROR] Part '{result.part_id}' ({result.part_name}) failed to generate:\n"
                f"    // {result.error}\n"
            )
        else:
            indented = textwrap.indent(result.code.strip(), "        ")
            section = (
                f"    // ── {result.part_name} ({result.part_id}) ──────────────────\n"
                f"    {{\n"
                + indented
                + ("\n" if indented else "")
                + "    }\n"
            )
        part_sections.append(section)

    combined_body = "\n".join(part_sections)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header_comment = (
        f"// Generated by fs-builder on {timestamp}\n"
        f"// Assembly: {assembly_name}\n"
        f"// {plan.description}\n"
        + (
            "".join(f"// [ERROR] Part '{part_id}' failed: {message}\n" for part_id, message in errors)
            if errors
            else ""
        )
        + "\n"
    )
    feature_block = _FEATURE_TEMPLATE.format(
        feature_name=display_name,
        func_name=func_name,
        body=combined_body,
    )
    return header_comment + _FS_HEADER + "\n" + feature_block


def _to_camel_case(snake_case: str) -> str:
    parts = snake_case.split("_")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])
